version: "3.9"
name: dremio_datalake
services:
  # MinIO
  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: minio
    ports:
      - '9000:9000'  # API
      - '9001:9001'  # Web Interface
    volumes:
      - './data/minio_data:/data'
    environment:
      MINIO_ROOT_USER: minio_root
      MINIO_ROOT_PASSWORD: minio_toor
    command: server --console-address ":9001" --address ":9000" /data
    networks:
      - dremio_datalake
    healthcheck:
      test: curl --fail -I http://localhost:9000/minio/health/live || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  # Metabase
  metabase:
    image: metabase/metabase:v0.50.28.3
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
      - ./configs/metabase:/tmp/metabase
      # Dremio Driver Plugin:  https://github.com/Baoqi/metabase-dremio-driver
      - ./configs/metabase/plugins/dremio.metabase-driver.jar:/plugins/dremio.metabase-driver.jar
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /tmp/metabase/metabaseappdb.h2
    networks:
      - dremio_datalake
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    
  # Dremio
  dremio-oss:
    depends_on:
      - minio
    image: dremio/dremio-oss:25.1
    container_name: dremio
    ports:
      - 9047:9047   # Web interface
      - 31010:31010 # ODBC/JDBC clients
      - 32010:32010 # Apache Arrow Flight clients
      - 45678:45678
    healthcheck:
      test: curl --fail -I http://localhost:9047/live || exit 1
      interval: 30s
      timeout: 3s
      retries: 20
    networks:
      - dremio_datalake
    
networks:
  dremio_datalake:
    driver: bridge
